require_relative 'logging.rb'
require_relative 'helpers.rb'

task :default => [:example]

desc "Just an example"
task :example => [:example_impl] do end

desc "Install dependencies required to run the app"
task :install => [:install_dependencies] do end

desc "Install tools required to develop the app"
task :dev => [:install_dev_tools] do end



# ==================== Implementation ====================

task :install_dependencies do
  bundle install
end

task :install_dev_tools do
  sh('./bigbang.sh')
end

task :example_impl do
  log_step 'Doing stuff...'
  price = extract_price(get_data('bitcoin'))
  log 'done, price is ' + price.to_s
end
