require_relative 'logging.rb'
require_relative 'helpers.rb'

task :default => [:example]

desc "Just an example"
task :example => [:example_impl] do end

desc "Just an example"
task :install => [:install_dependencies] do end


# ==================== Implementation ====================

task :example_impl do
  log_step 'Doing stuff...'
  get_price 'bitcoin'
  log 'done'
end

task :install_dependencies do
  bundle install
end
